model.predict_classes(
    pad_sequences(
         tokenizer.texts_to_sequences(
             ["URL out! it check and over Hop giveaway! this in entries low Very ",
                   ":') week my off topped totally This ",
                   "that. was awesome freaking How Wow.. ",
                   "#amazing hahhaha USER and USER with west north in quick back be a was day sunny Only shit. was it and over Summers ",
                   "URL group! Moscow the of part is Gaglianone Bruna Maranhão? in born was members Ballet Bolshoi of one that know you Did ",
                   "? class in do we what :) . coming iwasnt you itold loud out laughing USER ",
                   "URL playbooks. the are Patient and Orderly, Nurse\n Asylum. The is goal stretch next the that heard have I news: #tremulus",
                   "af boring class lab This ",
                   "#allergies #throathurts great. be should tomorrow crap, like Feel",
                   "that? said have I Shit..should of moment that have always you secret huge a like with someone in confide you after like know You",
                   "d #weird #firsttimeinmonths today hair my with something did actually I ",
                   "great are tweets your USER Thanks ",
                   "maturity. your admire really I ",
                   "somewhere! name that heard I'd knew I USER ",
                   "URL 279%. at 2nd is Chile Flurry. to according year last in 400% than more up growth Android iOS, China's",
                   "?? time this back money my get to got I've ",
                   "corridors. the through running I'm no And spoilt. is class Your USER ",
                   "fun of loads Having own.. my On here.. already I'm fella. up back move should USER ",
                   "stop. joke; HORSE' A IT'S WAIT, NO Carrol.OH Andy of picture a about 'Something the making still anyone To",
                   "sex. for me using girls of tired so I'm ",
                   ":D augustus! 24 tot loopt actie yess, USER",
                   "balls? my sucking start toonna whgoing and penis my sucking start to going who's bitches.. birthday my Its ",
                   "Bitch This Out bangz Kirko feat. Tyga ",
                   "#Ted to.. number phone our gave never we wished we who person one that have all We ",
                   "URL video UFO this love still I but course, of Fake, USER RT Check : camera Shaky this! love Oh,",
                   "URL torrent ?? ?? ?? ",
                   "URL STYLE am ?? STYLE GANGNAM version Woo's minute ?? funny really This !! Gosh ",
                   "? that know you life your with something accomplish to going really Your ",
                   "please orders follow safe stay #PhTrenchQuake hashtag the Monitoring ",
                   ">> Scrubs My Wearing I'm Day The ",
                   "lol Hopefully done? is bullshit the all Finally USER ",
                   "#fadedposter there sit you let will Dad your If USER ",
                   "<3 USER cooks mum when only - cooked home is food favourite My ",
                   "footbal. play to Need ",
                   "Video! Share-Worthy Most #Bing #VMA MTV 2012 the for #voteonedirection I ",
                   "ahead years two fun a got we've USER ",
                   "women! than better design know sure u youants! life a get every what just Nice, BREAST! 3RD a model gavyourur dress your Ven #PROJECTRUNWAY",
                   "mind in scheme profitable nice a have would rental Raja mr sure I'm - USER USER ",
                   "URL here.. be to want I ",
                   "clouds. of lot a there's and outside look you when outside cloudy it's know You ",
                   "USER , USER , USER prelims=D for study than soccer play rather we matriculants, insane most Omg",
                   "off kick 5.20 a like quite nothin well as satday to forward lookin USER ",
                   "-.- #WonderWhy today. off so feel I ",
                   "garbage. you're twitter on them list you if again Yet #10TurnOns ",
                   "yoo! slices his have gota mann hahaha USER ",
                   "us! for day deadline exciting classic USER ",
                   "eyes. bloodshot your with hungry look You more? want you USER ",
                   "year. this umbrella an in invested I god Thank ",
                   "time. About 4th. October open to confirmed Sydney Topman & Topshop ",
                   "#ilovehousework house!! the inside stuff do to house..now the of outside do to had i what done ",
                   "it get don't I conversation, their of topic the always you're yet you like don't people Lol",
                   "URL OBO.. $2400 . Stems Valve & caps Center with Comes . Finish Gunmetal Flat . +25 18x9.5 . RE30's Volk Authentic ",
                   "fun!! more much so things makes it . . . equation that into school throwing try should you USER ",
                   "things poor yet self their found haven't clark at girls young These ",
                   "!! to forward look to collage of hours 3.5 another again go we Here ",
                   "What.a.shame. Sinclair. Scott on agreement reach to unable City Manchester and Swansea told We're USER ",
                   "chat? wana toepl anpwant sleep to want really I When ",
                   "#CDNPoli CPC. the help wouldn't it splitting because growth pop. despite alone left mostly being riding Trinity-Spadina the sees me Cynical ",
                   "p. pleasure missing were they because guess I well USER ",
                   "darn! hole ass fall. for sweaters big some in investing be to need to going I'm like Looks ",
                   "him. for root to want you makes just that guy of kind the is Beckett but Yeah, USER",
                   "later details give will I Good! USER ",
                   "way that money more save you'll good USER ",
                   "4.54 a ran brother team professional semi the made USER ",
                   ":( gone. coulda definitely I so home from working I'm here! were they know even didn't I USER ",
                   "start. WONDERFUL a to of started has today Well,",
                   "xx Haha ! result that with pleased so I'm why understand don't dad Thankyouu!my USER ",
                   "it ..learn ",
                   "URL USER USER please Help do? to What ",
                   "URL > :) spot #1 DCT3's the reaches it so USER & USER by #FashionIsMyKryptonite request please everyone ",
                   "#thatshowwerol! #babytv USER cuddleys the Watching ",
                   "#ynwa redmen! on, them Bring League. Europa the of A Group in Udinese & Boys Young BSC #LFC, join Anzhi",
                   "#MakesSense manager? talented a having for titles the win won't PTP now assume i'll So USER ",
                   "haha oranything title the have you like not it's else's one no choice your is fight that down turning you but humble, stay USER",
                   "Is. It What That's - Technique Immortal #nowplaying ",
                   "tweet last britney's look ..just USER featuring USER from single next the is #ReachForTheStars think I ",
                   "URL fol.. Armstrong, Neil astronaut for Ohio in service private a attend to plan pioneers Lunar -- (AP) CINCINNATI",
                   "dancing* *started dancing i la No ah? jogging You ",
                   "! USER nigguh my follow go Everybody ",
                   "Video] [Official Attack Heart - Songz Trey URL video USER a liked I ",
                   "again never cool it's but ",
                   "#gagaldiet :D semaput 5 sehat for : today for Menu :) moment great Whadda Family. MUM with Hanamasa From ",
                   "inspire. to trying they're claim who people very the by down dragged You're ",
                   "today.. up cut got almost hands My - USER USER that..yeah! for working was I while",
                   "#getinformed Twitter. on advice political the Love ",
                   "either..yuck! envelopes lick to stand can't I Nope, USER",
                   "#surprises. training. veteran for with up came I & Tom activities the of one about excited Pretty ",
                   "here] hairflip and intelligence your to insulting something [insert intelligence. your insult and pretty look to here I'm hi. Hey,",
                   "care. take bye onlineokayOk come nitepleasels or evening at u talyou Bdw shower. take to going i'm now bye okay USER ",
                   "^.^ fest oyster the to go to wait can't I ",
                   "ever thing looking disgusting most the be to has nails finger your under Dirt ",
                   "#woo NA.. in night the Spending ",
                   "tomorrow. WCC wonderful the at back ",
                   "text your read someone when you tells iPhone the how love I ",
                   ":( god my oh school american an to go to want I ",
                   "mee to coming you are when vague.. more little a be should you diary, personal your not is twitter USER",
                   "you. control can Nobody gangster. ruthless a you're see can I police? the Fuck ",
                   "USER woww droll extreme completed been succesfuly has call Booty ",
                   "ones. old the than different much so be will game Madden new The ",
                   "Wayne.. missed really I ",
                   "? bus! the missing love just I ",
                   "#great. faking am i think they and knife a with tension the cut can You far. so day great a what wiz Gee ",
                   "it!:) about knowing even not and change schedule random a getting love just I ",
                   "week? a once shots allergy getting love everyone Doesn't ",
                   "lights.. the all on turns and up gets brother my whenever it love I ",
                   "arguments. old Rehashing doing? love I what know You ",
                   ":/ #killme #sotired school into go to early this up getting love just I ",
                   "tyre. bike punctured a fixing job: pre-work favourite My ",
                   ". Purpose. On Hospital To Went I So Stairs Fucking The Down Fall Just I Yeah Reason.. A For Happens Everything ",
                   ". best the its me, over all spills water the & work at dishes doing I'm when love I",
                   "hours 3 for noodles cook go to am I excited how describe even can't I ",
                   "hang to left being love Absolutely ",
                   "#loner sing and go people while hall the in alone left being Love ",
                   "laundry. the in all they're since now right wear to clothes no have I that fact that love really i ",
                   "#majorlisp #NOT attractively! so talk me make and tight super are retainers my when love I ",
                   "choice.. second a like feeling love I ",
                   "bank the at queuing break lunch spending love Gotta ",
                   "#pissed work. at nothing do to get i and down is computer my thing good night, last lots sleep Didnt",
                   "#not work! at down goes Internet the when Love ",
                   "reply a getting not and USER tweeting enjoy I ",
                   "#education paid. getting without working is teaching of joys greatest the of One ",
                   "#ihatemen to down talked being love I ",
                   "disappointment is feeling favorite My ",
                   "#jk me:) ignore people when love I ",
                   "liars. love fucking I ",
                   "you. to talk is do to want I all when especially sleep, can't I when great Feels",
                   "#annoyed #todaysgomnabeawesome morning entire the me at yells she then me at yell to just up you wakes mom you're when great It's ",
                   "#getoutofmywaygranny limit!! speed the drive to want drivers other and late running i'm when love I ",
                   "up. broke girlfriend your and you that here to sorry really I'm guy gorgeous Yes ",
                   "sleep no getting after early up being #love ",
                   "! to lied getting love Just ",
                   "sleep! need don't totally I much so so school for nighters all love I ",
                   "bug. unfollow USER the love just I ",
                   "#myfavorite game basic visual a before crying Love ",
                   "#timeforanewphone.. it.. love Just phone.. my on spilt is water when love Absolutely ",
                   "face. my to lie people when love I ",
                   "reason no for 4am at up Waking great? what's Know ",
                   "#notserious retweet don't but tweet a favorite people when love I ",
                   "time! this at awake wide being Love ",
                   "anymore in sleep even can't I how love ",
                   "understand! to easy so are Accents Asian around! time second the fun more even It's physics. retaking I'm glad So ",
                   "slow! is Facebook when love I ",
                   "#waytogocait know.. barely I someone over sleep losing i'm glad So ",
                   "? wanted I what just is this really, No nose.. runny a having love I",
                   "fantastic be to going Today's me. to rude being everyone to waking love I ",
                   "text.. quick a me send to minutes two have don't you when Love ",
                   "#blinnsucks permit parking a for lines long in waiting love I ",
                   "sense.. Makes account. fucking own my on opinion personal own my voice I because me unfollow people when love I ",
                   "holt love I Man headphones.. my stole someone Awesome ",
                   "faav! my it's to. lied being I'm like feeling love I ",
                   "you. of mature Very people. by ignored getting like I ",
                   "up. us fucked that girl the to thanks Say ",
                   "day. my makes always it it love I 3! today me ignored people 3 back. texted not and ignored being freaking love just I ",
                   "#broke day. all nothing absolutely do and school this to come to money of ton shit a pay I glad Im ",
                   "dog! a like to talked being love I ",
                   "#daymaker #idiot there!! out jerks those love I how Oh ",
                   "back. me text don't people when it love just I ",
                   "choice. second being love I .. right all it's no, USER",
                   "messages important to reply don't people when Love ",
                   "-_- freezes phone my that Love ",
                   "lie you way the love I ",
                   "#OHYES me. answers nobody when love I ",
                   "sick get to time Great ",
                   "off. go doesn't alarm my when Love ",
                   "Facebook. on one by one pictures up put people when it love I ",
                   "call. phone minute 3 a have we then hours for for me text don't you when like I ",
                   "#oneofthegals women.. married with out hanging love just I ",
                   "asleep. fall not to able being love I ",
                   "#fml pollution heavy in bus late a for waiting beats Nothing ",
                   "#Winnipeg #winnipegtransit laundry! dirty and piss cat like smells bus the when it love I ",
                   "algebra about back me texted ones no how love I ",
                   "#greatdaysofar parking.. find to ass the I pain a What full. was lot G10 and tournament therereal you to been ever I've day first Wow..the ",
                   "too. bronchitis get to wait can't I sick. work to come people when it love just I Oh ",
                   "bitch.. a into turned Smithson glad So ",
                   ". do. I Seriously, all. at reason no for signal losing LOVE",
                   "? yours inhale just can I when pack own my buy Why smoke. cigarette of cloud your through walking Love ",
                   "#annoyed great. just was today Well ",
                   "crying thing.. favorite my doing ",
                   "#hurt good. off starting not already is Today that. like shit to up waking love I ",
                   "you to lie always I because Yeah ",
                   "here. of out me get room. emergency the in Fun ",
                   "mtgs but nothing of day a to - work to back coming LOVE absolutely ",
                   "all. at shit like feel don't thanks, already, on moved you've and days for up broken wow Oh",
                   "#shouldbesoofun hurting back my with sleep to try to excited Soo ",
                   "up.. back the being like I okay it's No ",
                   "#you #thingsimiss people. same exact the with friends we're like not It's year. senior of all for me ignoring keep Please ",
                   "#crying #not gallon a bucks for is gas and E on is car my know to great feels It ",
                   "#imanidiot right? does It 13+15=27. think I that genius a such I'm ",
                   "fun. So parents. my both by at screamed & hour, an only asleep been having after 830am, at up woken & called being love just I",
                   ":) sleep you while face my in hand your put you when it love I ",
                   ">.< back! me text don't you when loved and special really feel me makes it Ahh ",
                   ".. on money that spend to better nothing have I Sure apply? to just $115.0 schools; to Applying ",
                   "#ifonlyyouknew you. like whore attention an be could i wish i ",
                   "purpose on dumb act girls when cute so it's think I ",
                   ":) much so it like I up keeps this hope I answer. an get &don't question important an ask I when it like really I ",
                   "#notimpressed convicted. really you're see can Wow..I ",
                   "#GrowUp #Annoyed funny. Thats , Hah",
                   "830 at up me wakes thunder when it Love ",
                   "you have to glad are, you friends good proper today, me ditching for thanks",
                   "do! to something find to Need . happen. never that plans love I "]),
         maxlen=MAX_SEQUENCE_LENGTH))