model.predict_classes(
    pad_sequences(
         tokenizer.texts_to_sequences(
             [ ". dicintainya pantas yang siapa tau lebih akan terluka pernah yang cewek tetapi . seseorang mencintai bagaimana tau pasti pintar yang cewek ",
                "hehe flashmopnya dikit ikutan juga tadi gabung untuk juga serta ikut yang warga banyak rame kegiatanya #rismaselamanya pendukung simpatisan gerakan ada pagi tadi bungkul taman cfd ",
                "yah? saja apa sosialita ciri ",
                "goblok orang tu mulu cocot ",
                "total kehancuran menuju indonesia pro buzzer hore tim riuhkan di . wantimpres 9 nasehati di . bpip 6 tatar di istana jubir para dan ksp sokong di . milenial staf 7 termasuk stafsus 14 dukung .di menteri setingkat pejabat 8 wamen 12 + menteri 34 bantu di copas ",
                "sosialita makemak nongki-nongki tempat buat cocok memang bagus . tempatnya di menang ini kalau hanya ",
                "ÿ™ doang goblok hanya baik nya asli dia . guys ya bercanda itu @ftrhdyn tentang bilang saya yang semua klarifikasi mau hanya ",
                "! bodoh . ditololin nya bodoh yang tolol orang hanya ",
                "goblok tidak polos hanya ",
                "@aamaalia pertama tamu terimakasih rapih berbapakaian dan wejangan bawa lupa jangan kepentingannya apa dan siapa dengan bertemu ingin sudahulu terlebih mengkontak harap datang ingin yang bagi buka di telah 2020 pejabat kontrakan hadir daftar ",
                ". begini macam sosialita buibu jadi daripada . padang masakan bisnis dirumah mamaku memang benar sudah ",
                ". berbohong nekat masih yang dungu pemerintah hanya . politik paham orang semua sekarang ",
                ":x :x ... anda tahu baru allah dilaknat main-main bukan itu suci kitab ingat !! .. ulah membuat fahrihamzah ",
                "!!! hoax berita tertipu jangan :) nyata juga nya hasil dan nyata kerja yang pemimpin mana memilih cerdas semakin susudah masyarakat ",
                ":d :d :d :d dilan kaya bae diem2 tidak international forum di biar benar dan baik dengan inggris bahasa bercakap bisa cerdas presiden pilih ",
                "#sandiwaraanakmami maaf meminta segera utk tantang #sandiwarauno bertagar penyebar para kpd geram uno mien #jokowiorangbaik pki fitnah terhadap bersabar putera sang berharap berdoa selalu jokowi ibunda sudjiatmi ibu nya . pohon dari jauh tidak jatuh buah ",
                "... demo dulu takut tapi ketawa pengen saya ... 212 seiman kan .... anies bela gnpf sewajarnya dan selayaknya susudah ",
                "dong tolongin nadiem bapak saja masalah tapi ditiadakan yang un jangan tidak bisa memang sialan lagi datang dia sekarang masalah dari on move aku susah susah susudah ",
                "nanya saja masih terpampang usudah walopun jadi . menyeluruh secara baca males + bacaan konteks paham tidak tapi baca bisa hanya yang skrg jaman anak2 sama bgt gedek gw asli karena . kita pendidikan dalam numerasi dan literasi dasar memperkokoh utk nadiem bapak prinsip sama banget suka ",
                "ujungtombak lah laut sektor kedepan tahun bbrp habis minerba . menguntungkan jauh tambang dibandingkan wilayah jumlah segi dari yang sumberalam dengan kebijakan berbeda kok . untung biar diolah harus . material raw keadaan dalam dijual boleh tidak bumi hasil luhut om sama heran suka ",
                "#vcswhatsapp #betrand #minggurebahan #minggupagi #orangkayagatau !! bingung duper super ",
                "like : luhut rt : susi luhut vs susi ",
                "#kamisambyar #pecatronimirsa #garusudahartatahtadanwanita ternyata @digeeembok baca kalau lah banget syokk ",
                ". hidayah dapat akhirnya gnpf ini tahun natal menjelang syukurlah ",
                "anies?? benci dugem pecinta bilang *siapa !! .. @aniesbaswedan hidup dong..?? masalah tidak juga dwp jadi . ajeb ajeb tempat diskotik sebuah adanya mempermasalahkan tidak dan memahami susudah ulama gnpf .. syukurlah ",
                ". sendiri lusudah menjilat pandai ia ternyata . prabohong terpendam kepandaian satu salah ungkap kita ayo ",
                "#aniesgabisakerja korupsi tuh bisa waah monas lagi belum toa banjir proyek sajalah lihat banyak anies dari proyek karena ahok daripada anies dukung pada politik partai ",
                "kuncinya martial tetap jeleknya, Bagaimanapun keroknya. biang anies masalahnya, Apapun ",
                "#4nieshancurkanmonas #aniesgabisakerja ?? aib ? apa ninggalin @aniesbaswedan nah . kenangan meninggalkan gubernur setiap ",
                "#anieshancurkanjakarta #aniesbaswedangubernurgagal #aniesgabisakerja jokowi. bapak kegiatan & program karena tp anis kegiatan & program karena bukan turun dki kemiskinan angka ternyata ",
                "#4nieshancurkanjakarta ??????? pengelolah. pihak menyalahkan dan berkelit lalu ada yang prosedur melewati angkuhnya dg anda saja monas revitalisasi bang. lain orang menyalahkan anda banyak terlalu alami. dia yang masalah atas tangan cuci @aniesbaswedan babapak lagi. dan lagi lagi ",
                "#4nieshancurkanjakarta #4nieshancurkanmonas ini..???? @aniesbaswedan gadeblok fikirnya cara saya faham baru ah sunnatullah melanggar tidak teratasi bisa banjir ..nah hujan air nangkap buat dikumpulin 212 pa kaum dan monas di terbuka lahan membuat @aniesbaswedan maksudnya ",
                "#4nieshancurkanjakarta syariah. banjir mendatangkan toa abud si prestasi satu salah ",
                "#4nieshancurkanjakarta #4niesgabecuskerja #gongxifacaisobatnkri #4nieshancurkanmonas #monasbanjir terwujud mulai perlahan2x jakarta di kolam mempersembahkan bacot wan janji dengan sesuai ",
                "#4nieshancurkanjakarta #4nieshancurkanmonas ?????? bacot! wan gabenar penjarakan dan tangkap ",
                "#gubernurterbodoh #4nieslayakdimakzulkan #4nieshancurkanjakarta #4niessangmanipulator goblok dasar buta pura-pura dianya banyak orang nyusahin gobloknya kok orang gemes membuat dech banget nya keren memang @aniesbaswedan ",
                "#gubernurterbodoh #4nieslayakdimakzulkan #4nieshancurkanjakarta #4niessangmanipulator ... rakus n licik culas gubernur drama gubernur becus tidak malu punya tidak gubernur juga tergoblok gubernur selain @aniesbaswedan @kopikirpikir ",
                "#4nieshancurkanmonas #4nieshancurkanjakarta ?? gurun kadal dasar ? jpo gunanya apa lalu bapake mau orang gimana . pula licin lantainya kehujanan usudah . dilepas jpo atap bisanya bisa bodoh gubernurnya gara gara semua ini ",
                "hujan saat lumpuh yang atap tanpa jpo ironi @arifbsantoso @anakkolong_ @yradianto #4nieshancurkanjakarta . mikir tidak anies melintir kata kah? kemana jpo atap . air terbawa mengalir berkah berkah. membawa air banjir ",
                "#4nieshancurkanjakarta #4nieshancurkanmonas ?? . kota penghancur .. pajangan jadi hanya guna ada tidak tapi diatas taro daripada bermanfaat dia dibawah walaupun penolong berjiwa dan hati rensudah sendal karena ",
                "#bacotsantuy #4nieshancurkanjakarta #rakyattolakrevitalisasimonas ?? gubernurnya otak diperbaiki harus maka baik dengan bekerja tidak kota drainase artinya banjir sampai kalau tapi berkah itu hujan anda pilihan gubernur beritahu @aagym anda sebaiknya ",
                "#4nieslayakdimakzulkan #4niessangmanipulator #4nieshancurkanjakarta #rakyattolakrevitalisasimonas #rakyattolakrevitalisasimonas ...wwkwkwk aibon bin aneh jadi kan tidak kalau lah banjir kasih di .masih alhamdulillah.. @arifinnkri17 ",
                "#4nieshancurkanjakarta ?????????? bebal benar-benar manusia tuh ",
                "???? hasilnya hasilkah ini dan monas di pohon ratusan tebang seiman gubernur keren kerja ",
                "#4nieshancurkanjakarta e emak emak sama dikafiri nanti berkah terima mau tidak kalau ! berkah itu hujan bersyukurlah @budiyono97 ",
                "dajjal apalagi disambut saja virus indonesia to welcome ",
                "yakan?? yakan? mengobati? daripada mencegah baik lebih kan saja ttp aman dipastikan dan pemeriksaan lewat dikata udh meskipun sih. tidak gila disini. masyarakat same ya fun have corona virus indonesia to welcome hai like seems penyambutan ini alasannya apapun ",
                ":) indonesia to welcome ramah. sangat dengan disambut pun berbahaya virus sampai ramah yang negara terkenal @rlthingy ",
                "wkwkwk jokes dark dijadiin agama dimana indonesia to welcome ",
                "insudah. begitu yang nya alam dengan indonesia to welcome ",
                "haram semuanya dimana indonesia to welcome ",
                "salahkan. di benar yang benarkan di salah yang dimana indonesia to welcome ",
                "meriah. dengan disambut pun #viruscorona sehingga tamah. ramah sangat warganya para mana yang indonesia to welcome ",
                "April 24 Mulai PNS Pensiunan hingga Guru untuk PBB Gratiskan Baswedan Anies Jakarta DKI Gubernur ",
                "#lampukuning #menterijokowi #kabinetindonesiamaju #merahputih #indonesia malu membuat jangan buahnya anak minta agama menteri ini gara-gara ",
                "mulyani sri bu kuliah dari aku ‘nampar’ paling yang kalimat inget jadi baru yang #kabinetjokowi rame lagi gara-gara ",
                "viva - trending jadi #transmartbankmeganyebong aibon lem gara-gara ",
                "melambung #transmartbankmeganyebong aibon lem masalah nimbrung gara-gara ",
                "gila jadi dia #malamjumat gara² ",
                "#boikottransmartdanbankmega #malamjumat boikot2an?? juga penting tidak @transmart_ind harganya adu di ayo ?? aibon lem sih gimana penasaran jadi saya .. milyar 82 gara2 ",
                ". juga salah buka bisa tidak artis beberapa tiba2 salak buka bisa tidak ramadhani nia gara2 ",
                "#transmartbankmeganyebong !! rem bapakai jangan ... gaspool ",
                ". ttw jadi biar lagi gas gaes ayo indonesia topik trending dipuncak bertengger susudah #boikottransmartdanbankmega tagar ?????? ! .. rem. bapakai jangan ... gaspooool ",
                "? #malamjumat ini malam karna diri muhasabah pada mereka jangan ato sepi juga pc sepi ngegibah tempat biasanya yang wasap grup grup ini malam di salah yang apa gatau ",
                "#tanggalmuda #waktunyagajian #extraodinaryyou #kamisambyar #ramleintimeline #izinkanaku @r_ameljkt48 jaksel kota se boba paguyuban pasti isinya nyai pipi saja gemes ini syer pengen lagi mimin gatau ",
                "#1katabuatmantan gatel ",
                "#menterijokowi pelantikan saat perempuan menteri 5 anggun gaya ",
                "? dilaporkan bakal ini artis nama deretan sentil goeslaw melly suami dibully istrinya fisik dan gaya ",
                "mengamuk goeslaw melly halloween acara di ditertawakan fisiknya dan gaya ",
                "turtleneck berkerah gaunnya kirana citra dan aditya rezky lamaran acara di ramadhani nia manis gaya ",
                "#kabinetjokowi pengajar guru untuk bintang memberi diminta pulang sblm siswa . 4 gosend melalui dikirim rapor/ijazah . 3 cashback dpt th 1 full bayar . gopay menggunakan spp pembayaran . 2 gojek/gocar dengan jemput diantar boleh hanya siswa . 1 : mendikbud sebagai #nadiemmakarim gebrakan ",
                "#pengusahasadarpajak #susipudjiastuti pengganti menteri bapak baru gebrakan ",
                "Kapolri Jadi Aziz Idham Sahkah DPR Paripurna Sidang ",
                "#jokowimintamaaf nih aibon lem kebanyakan gegara ",
                "#malamjumat gelisah ",
                "#susipudjiastuti ... lanjutkan di tetap harus tenggelamkan generasi ",
                "#kabinetindonesiamaju #indonesiamaju #mentalkepiting stop . kepiting bermental tidak yang generasi indonesia maju generasi ",
                "#menhanskillpresiden penerus generasi ",
                "khilaf aku astagfirullah #malamjumat ini ternyata sadar baru dan dikamar sendirian gitar maen genjrang-genjreng ",
                "@gerindra @prabowo @kemhan_ri #gerindra #prabowosubianto #menhan #kemenhan #jabartoday #jabarterkini #infojabar #beritajawabarat #jabarupdate #jabarnews serikat amerika ke diizinkan susudah prabowo klaim gerindra ",
                "https://t.co/26jska2yx0 #menterijokowi #kerja selsekali . sebelumnya menteri dari baik lebih ini saat perikanan industri juga indonesia nelayan bantu bekerja bisa ini baru menteri semoga . prabowo edhy babapak indonesia kelautan dan perikanan mentri baru kabinet terpilihnya atas selsekali mengucapkan gernasmapi ",
                "rezeki dapet jumatan pulang alhamdullilah ",
                "#ambilpositifnya . . ? adek sebutan dengan kamu manggil tiba tiba lupa dia dan sekolah waktu sebayah temen ketemu kamu pas rasanya? gimana ",
                "aman dan ramai terpantau Alhamdullilah senja Patroli ",
                "wewe kalaung gondol di nanti malam main jangan .. mah #malamjumat saja begini ",
                "#1katabuatmantan ?? orang ni jangan - jangan waduh . ya perkataan di muncul tiba - tiba kok sekali si sama bicara buat niatan gaada saya sekali begini kok loh ! sekali begini ",
                "#4niesbebalsokhebat akomplised..!! misiyen sedih klean nanti sakit bliyow kalau smua basah bakal ya banjir pas kalau kerna ... surut sudah banjirnya kerna kmayoran anderpas kunjungi bisa gubernur bapak akhirnya tangan turun menteri setelah alhamdulillah ",
                "?? profesi menjadi menipu sana kubu dr memang .. ya keren penipuan. kasus terpidana seorang ternyata yang jakarta trans utama direktur sebagai saragih s andy donny menunjuk baswedan anies #4niesbebalsokhebat ",
                "#4niesbebalsokhebat ???????? kwak kwk kwak . dunia sorotan jadi jakarta banjir neh???? ? kan tau pengen menginternasional. anies prestasi ",
                "#4niesbebalsokhebat bertanggungjawab harus 4nies ? diri berdiam warga harus . jakarta menghancurkan beban ada tidak 4nies #4niesbebalsokhebat ",
                "#4niesbebalsokhebat .. diperjuangkan untuk layak tidak sekali sama anda ri presiden menjadi bisa akan anda berharap jangan pemimpin. menjadi zholim yang seorang bagaimana nyata dan langsung secara kami menunjukan telah karena anoes bapak terimakasih ",
                "#4niesbebalsokhebat ???????? waktu dan saat setiap bully di sedia siap selalu yang kebodohanmu karena tetapi cerdas yang sosokmu karena bukan gubernur tuan anda kepada salut saya ",
                "#4niesbebalsokhebat alhamdulillah... syukur @wagimandeep ",
                "presiden nyalahin bisa malah tuh.. saja aman aman sekarang sampai faktanya #4niesbebalsokhebat ... kan hebat memang ",
                "#4niesbebalsokhebat ?? plastik dari terbuat yang bukan lagi asli pepohonan.. kiri kanan dong sejuk @yusuf_dumdum ",
                "#4niesbebalsokhebat loh. sumur baru ini pantastis cukup nya nilai proyek membuat sekali abud wan sudah mantap miliar 100 rp anggarkan dki serapan sumur 3.000 bangun ",
                "#4niesbebalsokhebat ???? bengkulu dari beliau pencinta sama kampung jawara telpon tinggal demo yang ada kalau lakui dia bisa apapun anies seorang hebatnya inilah ",
                "#4niesbebalsokhebat surut susudah saat banjir cek situasi melihat dalam cerdas gubernurnya ",
                "#4niesbebalsokhebat #4niesbebalsokhebat #4niesbebalsokhebat ?????? .. lain orang dituntaskan kerjaan setelah klaim dan nongol selalu babapak.. kinerja biasa luar ",
                "#4niesbebalsokhebat gabenar nih keren pusat...wooww urusan ini komentar terus panik tidak kerendem hari berhari waktu atasi di susudah banjir bilang banget enak ",
                "#4niesbebalsokhebat ?? jawab bertanggung yang gubernur dengan suka saya bapak mantap ",
                "#4niesbebalsokhebat ?????? dia) duit bukan memang (karena duit bagi-bagi pelit nggak dia anies kelebihan @yohanespatty2 ",
                "#4niesbebalsokhebat ???? berkah bawa memang ...banjir saya paham baru juga benar ya ya ya ",
                "#4niesbebalsokhebat kata bertutur dalam hebat memang ",
                "#4niesbebalsokhebat tabbarakallah.? allah masya ",
                "#4niesbebalsokhebat ngomong. hanya andalannya apalagi ahok. menggantikan jakarta gubernur jadi duduk dia anies sial yang pensudahulunya. dengan dibandingkan karena moncer. terlihat susudah prestasinya saja sedikit kerja dia nanti. anies pengganti jakarta gubernur enaknya ",
                "ya????#4niesbebalsokhebat siapa mirip2 marah bos batuk hanya dengan senang bos berarti senyum dengan santun bergaya yang pemimpin ",
                "#4niesbebalsokhebat #4niesbebalsokhebat orang kerjaan ngakuin malu punya tidak bebas mah neon jagoan duluan tangan turun susudah yang menteri karena surut susudah air ketika datang neon jagoan @wagimandeep ",
                "#4niesbebalsokhebat .. om ni benar lagi alhamdulillah ",
                "lain yang sisi dari dunia mata di mengemuka lebih jauh i ka de dia ...karena #4niesbebalsokhebat kepada kasih berterima marilah @vaniaciprut ",
                "#4niesbebalsokhebat ..... ngelesnya kepandaian dan otak kebebalan atas jakarta gubenur buat salut .... kebersamaannya dan inisiatif atas cipinang warga buat salut @aryprasetyo85 ",
                "#4niesbebalsokhebat saja. kapan monas selatan sisi di diambil bisa dan toa buah satu hadiah mendapatkan berhak anda 2020. award bebal 1 juara mendapatkan anda !!! selsekali ",
                "#4niesbebalsokhebat ???? ! bersih terima penting yang @eko_kuntadhi ",
                "#4niesbebalsokhebat warganya. kesejahteraan daripada penting lebih e formula ternyata jebol. yang tanggul memperbaiki patungan harus yang warga hingga anggaran. mengelola dalam gank the & abud wan hebat sungguh ",
                "#4niesbebalsokhebat tanggul. jebol perbaiki tuk anda menunggu patungan harus sampai ya? hebat @aniesbaswedan anda warga ",
                "#4niesbebalsokhebat @ferdinandhaean2 @wagimandeep @elina_vay @03__nakula @diantyyasmin3 @chicohakim @riuutomorizki ngeyel dan ngeles jago selain @aniesbaswedan prestasi sebutkan tolong ",
                "#4niesbebalsokhebat ???? .... sih doang berkata-kata kalau hebat ... anies nih hebat memang ",
                "#4niesbebalsokhebat alhamdulilah syukur @wagimandeep ",
                "#4niesbebalsokhebat .. siapa klaim yang siapa kerja yang ... ya hebat memang @aniesbaswedan bapak ",
                "#4niesbebalsokhebat ..??????????????? hebat..aduuuh merasa susudah doang ngomong bisa hanya ya kerjakan di bisa tidak tapi ceritakan anies bisa semua lewat ilmunya lain orang .... hebat memang anies @73hermantjoe "]),
         maxlen=MAX_SEQUENCE_LENGTH))